// <auto-generated />
/*
 * Bastille.ID Identity Server
 * (c) Copyright Talegen, LLC.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/
namespace Bastille.Id.Server.Properties
{
    /// <summary>
    /// This class is automatically generated and will create resource keys for use within the application.
    /// </summary>
    public static class ResourceKeys
    {
        /// <summary>
        /// Gets the key for the AccessDeniedErrorText resource string.
        /// </summary>
        public const string AccessDeniedErrorText = "AccessDeniedErrorText"; 

        /// <summary>
        /// Gets the key for the ActivityLogText resource string.
        /// </summary>
        public const string ActivityLogText = "ActivityLogText"; 

        /// <summary>
        /// Gets the key for the AddressText resource string.
        /// </summary>
        public const string AddressText = "AddressText"; 

        /// <summary>
        /// Gets the key for the AddText resource string.
        /// </summary>
        public const string AddText = "AddText"; 

        /// <summary>
        /// Gets the key for the AddUserAltText resource string.
        /// </summary>
        public const string AddUserAltText = "AddUserAltText"; 

        /// <summary>
        /// Gets the key for the AddUserText resource string.
        /// </summary>
        public const string AddUserText = "AddUserText"; 

        /// <summary>
        /// Gets the key for the AllDatesAndTimesText resource string.
        /// </summary>
        public const string AllDatesAndTimesText = "AllDatesAndTimesText"; 

        /// <summary>
        /// Gets the key for the AllOrganizationsDropDownText resource string.
        /// </summary>
        public const string AllOrganizationsDropDownText = "AllOrganizationsDropDownText"; 

        /// <summary>
        /// Gets the key for the AlreadyAuthenticatedErrorText resource string.
        /// </summary>
        public const string AlreadyAuthenticatedErrorText = "AlreadyAuthenticatedErrorText"; 

        /// <summary>
        /// Gets the key for the AlreadyLoggedOutErrorText resource string.
        /// </summary>
        public const string AlreadyLoggedOutErrorText = "AlreadyLoggedOutErrorText"; 

        /// <summary>
        /// Gets the key for the ApiGrantsText resource string.
        /// </summary>
        public const string ApiGrantsText = "ApiGrantsText"; 

        /// <summary>
        /// Gets the key for the ApisText resource string.
        /// </summary>
        public const string ApisText = "ApisText"; 

        /// <summary>
        /// Gets the key for the ApplicationInUseErrorText resource string.
        /// </summary>
        public const string ApplicationInUseErrorText = "ApplicationInUseErrorText"; 

        /// <summary>
        /// Gets the key for the ApplicationName resource string.
        /// </summary>
        public const string ApplicationName = "ApplicationName"; 

        /// <summary>
        /// Gets the key for the ApplicationNameExistsText resource string.
        /// </summary>
        public const string ApplicationNameExistsText = "ApplicationNameExistsText"; 

        /// <summary>
        /// Gets the key for the ApplicationPictureAltText resource string.
        /// </summary>
        public const string ApplicationPictureAltText = "ApplicationPictureAltText"; 

        /// <summary>
        /// Gets the key for the ApplicationsText resource string.
        /// </summary>
        public const string ApplicationsText = "ApplicationsText"; 

        /// <summary>
        /// Gets the key for the ArgumentMustBeGreaterThanZeroErrorFormat resource string.
        /// </summary>
        public const string ArgumentMustBeGreaterThanZeroErrorFormat = "ArgumentMustBeGreaterThanZeroErrorFormat"; 

        /// <summary>
        /// Gets the key for the AuthenticateText resource string.
        /// </summary>
        public const string AuthenticateText = "AuthenticateText"; 

        /// <summary>
        /// Gets the key for the AuthenticationInvalidRequestErrorTitleText resource string.
        /// </summary>
        public const string AuthenticationInvalidRequestErrorTitleText = "AuthenticationInvalidRequestErrorTitleText"; 

        /// <summary>
        /// Gets the key for the AuthenticationNoSchemesErrorText resource string.
        /// </summary>
        public const string AuthenticationNoSchemesErrorText = "AuthenticationNoSchemesErrorText"; 

        /// <summary>
        /// Gets the key for the AuthenticatorAppVerifiedLogText resource string.
        /// </summary>
        public const string AuthenticatorAppVerifiedLogText = "AuthenticatorAppVerifiedLogText"; 

        /// <summary>
        /// Gets the key for the AuthenticatorAppVerifiedText resource string.
        /// </summary>
        public const string AuthenticatorAppVerifiedText = "AuthenticatorAppVerifiedText"; 

        /// <summary>
        /// Gets the key for the AvailableOrganizationsText resource string.
        /// </summary>
        public const string AvailableOrganizationsText = "AvailableOrganizationsText"; 

        /// <summary>
        /// Gets the key for the BackText resource string.
        /// </summary>
        public const string BackText = "BackText"; 

        /// <summary>
        /// Gets the key for the BackToLoginText resource string.
        /// </summary>
        public const string BackToLoginText = "BackToLoginText"; 

        /// <summary>
        /// Gets the key for the BackToSettingsText resource string.
        /// </summary>
        public const string BackToSettingsText = "BackToSettingsText"; 

        /// <summary>
        /// Gets the key for the CancelText resource string.
        /// </summary>
        public const string CancelText = "CancelText"; 

        /// <summary>
        /// Gets the key for the ChangePhotoText resource string.
        /// </summary>
        public const string ChangePhotoText = "ChangePhotoText"; 

        /// <summary>
        /// Gets the key for the ClaimsText resource string.
        /// </summary>
        public const string ClaimsText = "ClaimsText"; 

        /// <summary>
        /// Gets the key for the ClientApplicationAccessDetailsText resource string.
        /// </summary>
        public const string ClientApplicationAccessDetailsText = "ClientApplicationAccessDetailsText"; 

        /// <summary>
        /// Gets the key for the ClientApplicationAccessText resource string.
        /// </summary>
        public const string ClientApplicationAccessText = "ClientApplicationAccessText"; 

        /// <summary>
        /// Gets the key for the ClientApplicationNoneFoundText resource string.
        /// </summary>
        public const string ClientApplicationNoneFoundText = "ClientApplicationNoneFoundText"; 

        /// <summary>
        /// Gets the key for the ClientConsentsText resource string.
        /// </summary>
        public const string ClientConsentsText = "ClientConsentsText"; 

        /// <summary>
        /// Gets the key for the ClientRevokedMessageText resource string.
        /// </summary>
        public const string ClientRevokedMessageText = "ClientRevokedMessageText"; 

        /// <summary>
        /// Gets the key for the ClientsText resource string.
        /// </summary>
        public const string ClientsText = "ClientsText"; 

        /// <summary>
        /// Gets the key for the CloseText resource string.
        /// </summary>
        public const string CloseText = "CloseText"; 

        /// <summary>
        /// Gets the key for the CodeRequiredErrorText resource string.
        /// </summary>
        public const string CodeRequiredErrorText = "CodeRequiredErrorText"; 

        /// <summary>
        /// Gets the key for the ConfigureAuthenticatorAppText resource string.
        /// </summary>
        public const string ConfigureAuthenticatorAppText = "ConfigureAuthenticatorAppText"; 

        /// <summary>
        /// Gets the key for the ConfirmationRequirementsText resource string.
        /// </summary>
        public const string ConfirmationRequirementsText = "ConfirmationRequirementsText"; 

        /// <summary>
        /// Gets the key for the ConfirmPasswordText resource string.
        /// </summary>
        public const string ConfirmPasswordText = "ConfirmPasswordText"; 

        /// <summary>
        /// Gets the key for the ConsentMessageText resource string.
        /// </summary>
        public const string ConsentMessageText = "ConsentMessageText"; 

        /// <summary>
        /// Gets the key for the ContactNameText resource string.
        /// </summary>
        public const string ContactNameText = "ContactNameText"; 

        /// <summary>
        /// Gets the key for the CreatedText resource string.
        /// </summary>
        public const string CreatedText = "CreatedText"; 

        /// <summary>
        /// Gets the key for the CreateOneText resource string.
        /// </summary>
        public const string CreateOneText = "CreateOneText"; 

        /// <summary>
        /// Gets the key for the CryptoAuthKeyLengthErrorText resource string.
        /// </summary>
        public const string CryptoAuthKeyLengthErrorText = "CryptoAuthKeyLengthErrorText"; 

        /// <summary>
        /// Gets the key for the CryptoKeyLengthErrorText resource string.
        /// </summary>
        public const string CryptoKeyLengthErrorText = "CryptoKeyLengthErrorText"; 

        /// <summary>
        /// Gets the key for the CryptoMustSpecifyCryptoTextToDecryptErrorText resource string.
        /// </summary>
        public const string CryptoMustSpecifyCryptoTextToDecryptErrorText = "CryptoMustSpecifyCryptoTextToDecryptErrorText"; 

        /// <summary>
        /// Gets the key for the CryptoMustSpecifyTextToEncryptErrorText resource string.
        /// </summary>
        public const string CryptoMustSpecifyTextToEncryptErrorText = "CryptoMustSpecifyTextToEncryptErrorText"; 

        /// <summary>
        /// Gets the key for the CurrentOrganizationsText resource string.
        /// </summary>
        public const string CurrentOrganizationsText = "CurrentOrganizationsText"; 

        /// <summary>
        /// Gets the key for the CurrentPasswordText resource string.
        /// </summary>
        public const string CurrentPasswordText = "CurrentPasswordText"; 

        /// <summary>
        /// Gets the key for the DashboardText resource string.
        /// </summary>
        public const string DashboardText = "DashboardText"; 

        /// <summary>
        /// Gets the key for the DataMigrationErrorText resource string.
        /// </summary>
        public const string DataMigrationErrorText = "DataMigrationErrorText"; 

        /// <summary>
        /// Gets the key for the DataPersistanceInfoText resource string.
        /// </summary>
        public const string DataPersistanceInfoText = "DataPersistanceInfoText"; 

        /// <summary>
        /// Gets the key for the DeleteAccountConfirmApplications resource string.
        /// </summary>
        public const string DeleteAccountConfirmApplications = "DeleteAccountConfirmApplications"; 

        /// <summary>
        /// Gets the key for the DeleteAccountConfirmation resource string.
        /// </summary>
        public const string DeleteAccountConfirmation = "DeleteAccountConfirmation"; 

        /// <summary>
        /// Gets the key for the DeleteAccountConfirmOrganizations resource string.
        /// </summary>
        public const string DeleteAccountConfirmOrganizations = "DeleteAccountConfirmOrganizations"; 

        /// <summary>
        /// Gets the key for the DeleteAccountFailLogText resource string.
        /// </summary>
        public const string DeleteAccountFailLogText = "DeleteAccountFailLogText"; 

        /// <summary>
        /// Gets the key for the DeleteAccountSuccessLogText resource string.
        /// </summary>
        public const string DeleteAccountSuccessLogText = "DeleteAccountSuccessLogText"; 

        /// <summary>
        /// Gets the key for the DeleteAccountText resource string.
        /// </summary>
        public const string DeleteAccountText = "DeleteAccountText"; 

        /// <summary>
        /// Gets the key for the DeleteAccountWarningText resource string.
        /// </summary>
        public const string DeleteAccountWarningText = "DeleteAccountWarningText"; 

        /// <summary>
        /// Gets the key for the DeleteText resource string.
        /// </summary>
        public const string DeleteText = "DeleteText"; 

        /// <summary>
        /// Gets the key for the DeleteUserConfirmationText resource string.
        /// </summary>
        public const string DeleteUserConfirmationText = "DeleteUserConfirmationText"; 

        /// <summary>
        /// Gets the key for the DeleteUserText resource string.
        /// </summary>
        public const string DeleteUserText = "DeleteUserText"; 

        /// <summary>
        /// Gets the key for the DeniedText resource string.
        /// </summary>
        public const string DeniedText = "DeniedText"; 

        /// <summary>
        /// Gets the key for the DeserializeFileNotFoundErrorText resource string.
        /// </summary>
        public const string DeserializeFileNotFoundErrorText = "DeserializeFileNotFoundErrorText"; 

        /// <summary>
        /// Gets the key for the DetailsLinkText resource string.
        /// </summary>
        public const string DetailsLinkText = "DetailsLinkText"; 

        /// <summary>
        /// Gets the key for the DevBlogText resource string.
        /// </summary>
        public const string DevBlogText = "DevBlogText"; 

        /// <summary>
        /// Gets the key for the DiagnosticsText resource string.
        /// </summary>
        public const string DiagnosticsText = "DiagnosticsText"; 

        /// <summary>
        /// Gets the key for the DisabledLowerText resource string.
        /// </summary>
        public const string DisabledLowerText = "DisabledLowerText"; 

        /// <summary>
        /// Gets the key for the EditProfileText resource string.
        /// </summary>
        public const string EditProfileText = "EditProfileText"; 

        /// <summary>
        /// Gets the key for the EmailAccountText resource string.
        /// </summary>
        public const string EmailAccountText = "EmailAccountText"; 

        /// <summary>
        /// Gets the key for the EmailConfirmedMessageText resource string.
        /// </summary>
        public const string EmailConfirmedMessageText = "EmailConfirmedMessageText"; 

        /// <summary>
        /// Gets the key for the EmailConfirmedPromptText resource string.
        /// </summary>
        public const string EmailConfirmedPromptText = "EmailConfirmedPromptText"; 

        /// <summary>
        /// Gets the key for the EmailConfirmedText resource string.
        /// </summary>
        public const string EmailConfirmedText = "EmailConfirmedText"; 

        /// <summary>
        /// Gets the key for the EmailConfirmErrorText resource string.
        /// </summary>
        public const string EmailConfirmErrorText = "EmailConfirmErrorText"; 

        /// <summary>
        /// Gets the key for the EmailInvalidText resource string.
        /// </summary>
        public const string EmailInvalidText = "EmailInvalidText"; 

        /// <summary>
        /// Gets the key for the EmailText resource string.
        /// </summary>
        public const string EmailText = "EmailText"; 

        /// <summary>
        /// Gets the key for the EnterCodeText resource string.
        /// </summary>
        public const string EnterCodeText = "EnterCodeText"; 

        /// <summary>
        /// Gets the key for the EnterRecoveryCodeText resource string.
        /// </summary>
        public const string EnterRecoveryCodeText = "EnterRecoveryCodeText"; 

        /// <summary>
        /// Gets the key for the EnterYourEmailAddressText resource string.
        /// </summary>
        public const string EnterYourEmailAddressText = "EnterYourEmailAddressText"; 

        /// <summary>
        /// Gets the key for the ErrorCreateDirectoryText resource string.
        /// </summary>
        public const string ErrorCreateDirectoryText = "ErrorCreateDirectoryText"; 

        /// <summary>
        /// Gets the key for the ErrorDialogText resource string.
        /// </summary>
        public const string ErrorDialogText = "ErrorDialogText"; 

        /// <summary>
        /// Gets the key for the ErrorOccuredTryAgainText resource string.
        /// </summary>
        public const string ErrorOccuredTryAgainText = "ErrorOccuredTryAgainText"; 

        /// <summary>
        /// Gets the key for the ErrorText resource string.
        /// </summary>
        public const string ErrorText = "ErrorText"; 

        /// <summary>
        /// Gets the key for the ExpirationDateMustBeInFutureErrorText resource string.
        /// </summary>
        public const string ExpirationDateMustBeInFutureErrorText = "ExpirationDateMustBeInFutureErrorText"; 

        /// <summary>
        /// Gets the key for the ExpiresText resource string.
        /// </summary>
        public const string ExpiresText = "ExpiresText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataConsentsText resource string.
        /// </summary>
        public const string ExportPersonalDataConsentsText = "ExportPersonalDataConsentsText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataFailLogText resource string.
        /// </summary>
        public const string ExportPersonalDataFailLogText = "ExportPersonalDataFailLogText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataMessageText resource string.
        /// </summary>
        public const string ExportPersonalDataMessageText = "ExportPersonalDataMessageText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataOptionsText resource string.
        /// </summary>
        public const string ExportPersonalDataOptionsText = "ExportPersonalDataOptionsText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataOrganizationText resource string.
        /// </summary>
        public const string ExportPersonalDataOrganizationText = "ExportPersonalDataOrganizationText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataSuccessLogText resource string.
        /// </summary>
        public const string ExportPersonalDataSuccessLogText = "ExportPersonalDataSuccessLogText"; 

        /// <summary>
        /// Gets the key for the ExportPersonalDataText resource string.
        /// </summary>
        public const string ExportPersonalDataText = "ExportPersonalDataText"; 

        /// <summary>
        /// Gets the key for the ExportText resource string.
        /// </summary>
        public const string ExportText = "ExportText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationAccessDeniedText resource string.
        /// </summary>
        public const string ExternalAuthenticationAccessDeniedText = "ExternalAuthenticationAccessDeniedText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationAlreadyBoundErrorText resource string.
        /// </summary>
        public const string ExternalAuthenticationAlreadyBoundErrorText = "ExternalAuthenticationAlreadyBoundErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationAlreadyBoundMessageText resource string.
        /// </summary>
        public const string ExternalAuthenticationAlreadyBoundMessageText = "ExternalAuthenticationAlreadyBoundMessageText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationBindFailureErrorText resource string.
        /// </summary>
        public const string ExternalAuthenticationBindFailureErrorText = "ExternalAuthenticationBindFailureErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationProviderForUserNotFoundErrorText resource string.
        /// </summary>
        public const string ExternalAuthenticationProviderForUserNotFoundErrorText = "ExternalAuthenticationProviderForUserNotFoundErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalAuthenticationUserNotFoundText resource string.
        /// </summary>
        public const string ExternalAuthenticationUserNotFoundText = "ExternalAuthenticationUserNotFoundText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginApplicationErrorText resource string.
        /// </summary>
        public const string ExternalLoginApplicationErrorText = "ExternalLoginApplicationErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginDeletedMessageText resource string.
        /// </summary>
        public const string ExternalLoginDeletedMessageText = "ExternalLoginDeletedMessageText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginDeleteFailedErrorText resource string.
        /// </summary>
        public const string ExternalLoginDeleteFailedErrorText = "ExternalLoginDeleteFailedErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginMessageText resource string.
        /// </summary>
        public const string ExternalLoginMessageText = "ExternalLoginMessageText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginSuccessMessageText resource string.
        /// </summary>
        public const string ExternalLoginSuccessMessageText = "ExternalLoginSuccessMessageText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginText resource string.
        /// </summary>
        public const string ExternalLoginText = "ExternalLoginText"; 

        /// <summary>
        /// Gets the key for the ExternalLoginTitleText resource string.
        /// </summary>
        public const string ExternalLoginTitleText = "ExternalLoginTitleText"; 

        /// <summary>
        /// Gets the key for the ExternalProvidersLoadErrorText resource string.
        /// </summary>
        public const string ExternalProvidersLoadErrorText = "ExternalProvidersLoadErrorText"; 

        /// <summary>
        /// Gets the key for the ExternalProvisionDisabledErrorText resource string.
        /// </summary>
        public const string ExternalProvisionDisabledErrorText = "ExternalProvisionDisabledErrorText"; 

        /// <summary>
        /// Gets the key for the FailText resource string.
        /// </summary>
        public const string FailText = "FailText"; 

        /// <summary>
        /// Gets the key for the FirstNameRequiredText resource string.
        /// </summary>
        public const string FirstNameRequiredText = "FirstNameRequiredText"; 

        /// <summary>
        /// Gets the key for the FirstNameText resource string.
        /// </summary>
        public const string FirstNameText = "FirstNameText"; 

        /// <summary>
        /// Gets the key for the ForgotPasswordCheckEmailMessageText resource string.
        /// </summary>
        public const string ForgotPasswordCheckEmailMessageText = "ForgotPasswordCheckEmailMessageText"; 

        /// <summary>
        /// Gets the key for the ForgotPasswordMessageText resource string.
        /// </summary>
        public const string ForgotPasswordMessageText = "ForgotPasswordMessageText"; 

        /// <summary>
        /// Gets the key for the ForgotYourPasswordText resource string.
        /// </summary>
        public const string ForgotYourPasswordText = "ForgotYourPasswordText"; 

        /// <summary>
        /// Gets the key for the FullNameText resource string.
        /// </summary>
        public const string FullNameText = "FullNameText"; 

        /// <summary>
        /// Gets the key for the GrantedText resource string.
        /// </summary>
        public const string GrantedText = "GrantedText"; 

        /// <summary>
        /// Gets the key for the GroupCreateFailText resource string.
        /// </summary>
        public const string GroupCreateFailText = "GroupCreateFailText"; 

        /// <summary>
        /// Gets the key for the GroupCreateSuccessText resource string.
        /// </summary>
        public const string GroupCreateSuccessText = "GroupCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the GroupDeleteFailText resource string.
        /// </summary>
        public const string GroupDeleteFailText = "GroupDeleteFailText"; 

        /// <summary>
        /// Gets the key for the GroupDeleteSuccessText resource string.
        /// </summary>
        public const string GroupDeleteSuccessText = "GroupDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the GroupExistsFailText resource string.
        /// </summary>
        public const string GroupExistsFailText = "GroupExistsFailText"; 

        /// <summary>
        /// Gets the key for the GroupUpdateFailText resource string.
        /// </summary>
        public const string GroupUpdateFailText = "GroupUpdateFailText"; 

        /// <summary>
        /// Gets the key for the GroupUpdateSuccessText resource string.
        /// </summary>
        public const string GroupUpdateSuccessText = "GroupUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the HostTerminatedErrorText resource string.
        /// </summary>
        public const string HostTerminatedErrorText = "HostTerminatedErrorText"; 

        /// <summary>
        /// Gets the key for the IAgreeText resource string.
        /// </summary>
        public const string IAgreeText = "IAgreeText"; 

        /// <summary>
        /// Gets the key for the IdentifierPlaceholderEmailOrUserNameOrPhoneText resource string.
        /// </summary>
        public const string IdentifierPlaceholderEmailOrUserNameOrPhoneText = "IdentifierPlaceholderEmailOrUserNameOrPhoneText"; 

        /// <summary>
        /// Gets the key for the IdentifierPlaceholderEmailOrUserNameText resource string.
        /// </summary>
        public const string IdentifierPlaceholderEmailOrUserNameText = "IdentifierPlaceholderEmailOrUserNameText"; 

        /// <summary>
        /// Gets the key for the IdentityGrantsText resource string.
        /// </summary>
        public const string IdentityGrantsText = "IdentityGrantsText"; 

        /// <summary>
        /// Gets the key for the IdentityServerText resource string.
        /// </summary>
        public const string IdentityServerText = "IdentityServerText"; 

        /// <summary>
        /// Gets the key for the IdentityUserSyncFailedMessageText resource string.
        /// </summary>
        public const string IdentityUserSyncFailedMessageText = "IdentityUserSyncFailedMessageText"; 

        /// <summary>
        /// Gets the key for the IdentityUserSyncFailedSubjectText resource string.
        /// </summary>
        public const string IdentityUserSyncFailedSubjectText = "IdentityUserSyncFailedSubjectText"; 

        /// <summary>
        /// Gets the key for the IdentityUserSyncWebhookErrorText resource string.
        /// </summary>
        public const string IdentityUserSyncWebhookErrorText = "IdentityUserSyncWebhookErrorText"; 

        /// <summary>
        /// Gets the key for the IdentityWebhookCantConnectErrorText resource string.
        /// </summary>
        public const string IdentityWebhookCantConnectErrorText = "IdentityWebhookCantConnectErrorText"; 

        /// <summary>
        /// Gets the key for the IdentityWebhookSuccessText resource string.
        /// </summary>
        public const string IdentityWebhookSuccessText = "IdentityWebhookSuccessText"; 

        /// <summary>
        /// Gets the key for the IncludeInSubscriptionText resource string.
        /// </summary>
        public const string IncludeInSubscriptionText = "IncludeInSubscriptionText"; 

        /// <summary>
        /// Gets the key for the IncludeText resource string.
        /// </summary>
        public const string IncludeText = "IncludeText"; 

        /// <summary>
        /// Gets the key for the InvalidArgumentMustBeEnumerationText resource string.
        /// </summary>
        public const string InvalidArgumentMustBeEnumerationText = "InvalidArgumentMustBeEnumerationText"; 

        /// <summary>
        /// Gets the key for the InvalidAttributeOperationErrorText resource string.
        /// </summary>
        public const string InvalidAttributeOperationErrorText = "InvalidAttributeOperationErrorText"; 

        /// <summary>
        /// Gets the key for the InvalidFileArgumentErrorText resource string.
        /// </summary>
        public const string InvalidFileArgumentErrorText = "InvalidFileArgumentErrorText"; 

        /// <summary>
        /// Gets the key for the InvalidGrantMissingTokenParameterErrorText resource string.
        /// </summary>
        public const string InvalidGrantMissingTokenParameterErrorText = "InvalidGrantMissingTokenParameterErrorText"; 

        /// <summary>
        /// Gets the key for the InvalidPasswordResetCodeErrorText resource string.
        /// </summary>
        public const string InvalidPasswordResetCodeErrorText = "InvalidPasswordResetCodeErrorText"; 

        /// <summary>
        /// Gets the key for the InvalidRecoveryCodeText resource string.
        /// </summary>
        public const string InvalidRecoveryCodeText = "InvalidRecoveryCodeText"; 

        /// <summary>
        /// Gets the key for the InvalidReturnUrlText resource string.
        /// </summary>
        public const string InvalidReturnUrlText = "InvalidReturnUrlText"; 

        /// <summary>
        /// Gets the key for the InvalidSelectionErrorMessageText resource string.
        /// </summary>
        public const string InvalidSelectionErrorMessageText = "InvalidSelectionErrorMessageText"; 

        /// <summary>
        /// Gets the key for the InvalidWebhookUriErrorText resource string.
        /// </summary>
        public const string InvalidWebhookUriErrorText = "InvalidWebhookUriErrorText"; 

        /// <summary>
        /// Gets the key for the LanguageText resource string.
        /// </summary>
        public const string LanguageText = "LanguageText"; 

        /// <summary>
        /// Gets the key for the LastLoginText resource string.
        /// </summary>
        public const string LastLoginText = "LastLoginText"; 

        /// <summary>
        /// Gets the key for the LastNameRequiredText resource string.
        /// </summary>
        public const string LastNameRequiredText = "LastNameRequiredText"; 

        /// <summary>
        /// Gets the key for the LastNameText resource string.
        /// </summary>
        public const string LastNameText = "LastNameText"; 

        /// <summary>
        /// Gets the key for the LockDateTimeValidationText resource string.
        /// </summary>
        public const string LockDateTimeValidationText = "LockDateTimeValidationText"; 

        /// <summary>
        /// Gets the key for the LockedText resource string.
        /// </summary>
        public const string LockedText = "LockedText"; 

        /// <summary>
        /// Gets the key for the LockoutEndDateText resource string.
        /// </summary>
        public const string LockoutEndDateText = "LockoutEndDateText"; 

        /// <summary>
        /// Gets the key for the LockText resource string.
        /// </summary>
        public const string LockText = "LockText"; 

        /// <summary>
        /// Gets the key for the LockUserText resource string.
        /// </summary>
        public const string LockUserText = "LockUserText"; 

        /// <summary>
        /// Gets the key for the LoggedOutOfClientPromptText resource string.
        /// </summary>
        public const string LoggedOutOfClientPromptText = "LoggedOutOfClientPromptText"; 

        /// <summary>
        /// Gets the key for the LoggedOutPromptText resource string.
        /// </summary>
        public const string LoggedOutPromptText = "LoggedOutPromptText"; 

        /// <summary>
        /// Gets the key for the LoginAccountLockedMessageText resource string.
        /// </summary>
        public const string LoginAccountLockedMessageText = "LoginAccountLockedMessageText"; 

        /// <summary>
        /// Gets the key for the LoginRecoveryInvalidCodeErrorText resource string.
        /// </summary>
        public const string LoginRecoveryInvalidCodeErrorText = "LoginRecoveryInvalidCodeErrorText"; 

        /// <summary>
        /// Gets the key for the LoginRecoverySuccessMessageText resource string.
        /// </summary>
        public const string LoginRecoverySuccessMessageText = "LoginRecoverySuccessMessageText"; 

        /// <summary>
        /// Gets the key for the LoginRedirectWarningText resource string.
        /// </summary>
        public const string LoginRedirectWarningText = "LoginRedirectWarningText"; 

        /// <summary>
        /// Gets the key for the LoginReportDescriptionText resource string.
        /// </summary>
        public const string LoginReportDescriptionText = "LoginReportDescriptionText"; 

        /// <summary>
        /// Gets the key for the LoginReportLabelText resource string.
        /// </summary>
        public const string LoginReportLabelText = "LoginReportLabelText"; 

        /// <summary>
        /// Gets the key for the MobileText resource string.
        /// </summary>
        public const string MobileText = "MobileText"; 

        /// <summary>
        /// Gets the key for the MustChooseOneErrorMessageText resource string.
        /// </summary>
        public const string MustChooseOneErrorMessageText = "MustChooseOneErrorMessageText"; 

        /// <summary>
        /// Gets the key for the MyDashboardText resource string.
        /// </summary>
        public const string MyDashboardText = "MyDashboardText"; 

        /// <summary>
        /// Gets the key for the NewPasswordText resource string.
        /// </summary>
        public const string NewPasswordText = "NewPasswordText"; 

        /// <summary>
        /// Gets the key for the NoAccountQuestionText resource string.
        /// </summary>
        public const string NoAccountQuestionText = "NoAccountQuestionText"; 

        /// <summary>
        /// Gets the key for the NoApplicationsMessageText resource string.
        /// </summary>
        public const string NoApplicationsMessageText = "NoApplicationsMessageText"; 

        /// <summary>
        /// Gets the key for the NoText resource string.
        /// </summary>
        public const string NoText = "NoText"; 

        /// <summary>
        /// Gets the key for the OfflineAccessDescription resource string.
        /// </summary>
        public const string OfflineAccessDescription = "OfflineAccessDescription"; 

        /// <summary>
        /// Gets the key for the OfflineAccessDisplayName resource string.
        /// </summary>
        public const string OfflineAccessDisplayName = "OfflineAccessDisplayName"; 

        /// <summary>
        /// Gets the key for the OfText resource string.
        /// </summary>
        public const string OfText = "OfText"; 

        /// <summary>
        /// Gets the key for the OldPasswordRequirementText resource string.
        /// </summary>
        public const string OldPasswordRequirementText = "OldPasswordRequirementText"; 

        /// <summary>
        /// Gets the key for the OpenLinkText resource string.
        /// </summary>
        public const string OpenLinkText = "OpenLinkText"; 

        /// <summary>
        /// Gets the key for the OrganizationAccessForbiddenText resource string.
        /// </summary>
        public const string OrganizationAccessForbiddenText = "OrganizationAccessForbiddenText"; 

        /// <summary>
        /// Gets the key for the OrganizationCreateUserSuccessText resource string.
        /// </summary>
        public const string OrganizationCreateUserSuccessText = "OrganizationCreateUserSuccessText"; 

        /// <summary>
        /// Gets the key for the OrganizationDetailsText resource string.
        /// </summary>
        public const string OrganizationDetailsText = "OrganizationDetailsText"; 

        /// <summary>
        /// Gets the key for the OrganizationImageUpdateSuccessText resource string.
        /// </summary>
        public const string OrganizationImageUpdateSuccessText = "OrganizationImageUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the OrganizationsText resource string.
        /// </summary>
        public const string OrganizationsText = "OrganizationsText"; 

        /// <summary>
        /// Gets the key for the OrganizationText resource string.
        /// </summary>
        public const string OrganizationText = "OrganizationText"; 

        /// <summary>
        /// Gets the key for the OrganizationUpdatedSuccessfullyText resource string.
        /// </summary>
        public const string OrganizationUpdatedSuccessfullyText = "OrganizationUpdatedSuccessfullyText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserDeletedSuccessfulText resource string.
        /// </summary>
        public const string OrganizationUserDeletedSuccessfulText = "OrganizationUserDeletedSuccessfulText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserLockedSuccessfulText resource string.
        /// </summary>
        public const string OrganizationUserLockedSuccessfulText = "OrganizationUserLockedSuccessfulText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserPasswordChangedByManagerText resource string.
        /// </summary>
        public const string OrganizationUserPasswordChangedByManagerText = "OrganizationUserPasswordChangedByManagerText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserRemovedErrorText resource string.
        /// </summary>
        public const string OrganizationUserRemovedErrorText = "OrganizationUserRemovedErrorText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserRemovedSuccessText resource string.
        /// </summary>
        public const string OrganizationUserRemovedSuccessText = "OrganizationUserRemovedSuccessText"; 

        /// <summary>
        /// Gets the key for the OrganizationUsersText resource string.
        /// </summary>
        public const string OrganizationUsersText = "OrganizationUsersText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserUnlockedSuccessfulText resource string.
        /// </summary>
        public const string OrganizationUserUnlockedSuccessfulText = "OrganizationUserUnlockedSuccessfulText"; 

        /// <summary>
        /// Gets the key for the OrganizationUserUpdateEmailAlreadyExistsText resource string.
        /// </summary>
        public const string OrganizationUserUpdateEmailAlreadyExistsText = "OrganizationUserUpdateEmailAlreadyExistsText"; 

        /// <summary>
        /// Gets the key for the OrRegisterWithText resource string.
        /// </summary>
        public const string OrRegisterWithText = "OrRegisterWithText"; 

        /// <summary>
        /// Gets the key for the OrText resource string.
        /// </summary>
        public const string OrText = "OrText"; 

        /// <summary>
        /// Gets the key for the OverviewText resource string.
        /// </summary>
        public const string OverviewText = "OverviewText"; 

        /// <summary>
        /// Gets the key for the PageText resource string.
        /// </summary>
        public const string PageText = "PageText"; 

        /// <summary>
        /// Gets the key for the ParentOrganizationText resource string.
        /// </summary>
        public const string ParentOrganizationText = "ParentOrganizationText"; 

        /// <summary>
        /// Gets the key for the PasswordChangedStatusText resource string.
        /// </summary>
        public const string PasswordChangedStatusText = "PasswordChangedStatusText"; 

        /// <summary>
        /// Gets the key for the PasswordChangeSuccessText resource string.
        /// </summary>
        public const string PasswordChangeSuccessText = "PasswordChangeSuccessText"; 

        /// <summary>
        /// Gets the key for the PasswordConfirmationRequirementsText resource string.
        /// </summary>
        public const string PasswordConfirmationRequirementsText = "PasswordConfirmationRequirementsText"; 

        /// <summary>
        /// Gets the key for the PasswordlessAuthenticationEnableText resource string.
        /// </summary>
        public const string PasswordlessAuthenticationEnableText = "PasswordlessAuthenticationEnableText"; 

        /// <summary>
        /// Gets the key for the PasswordOrUserNameIncorrectText resource string.
        /// </summary>
        public const string PasswordOrUserNameIncorrectText = "PasswordOrUserNameIncorrectText"; 

        /// <summary>
        /// Gets the key for the PasswordRequiredText resource string.
        /// </summary>
        public const string PasswordRequiredText = "PasswordRequiredText"; 

        /// <summary>
        /// Gets the key for the PasswordResetConfirmationPromptText resource string.
        /// </summary>
        public const string PasswordResetConfirmationPromptText = "PasswordResetConfirmationPromptText"; 

        /// <summary>
        /// Gets the key for the PasswordResetFailInvalidUserMessageText resource string.
        /// </summary>
        public const string PasswordResetFailInvalidUserMessageText = "PasswordResetFailInvalidUserMessageText"; 

        /// <summary>
        /// Gets the key for the PasswordResetFailLogMessageText resource string.
        /// </summary>
        public const string PasswordResetFailLogMessageText = "PasswordResetFailLogMessageText"; 

        /// <summary>
        /// Gets the key for the PasswordResetLogMessageText resource string.
        /// </summary>
        public const string PasswordResetLogMessageText = "PasswordResetLogMessageText"; 

        /// <summary>
        /// Gets the key for the PasswordResetSuccessLogMessageText resource string.
        /// </summary>
        public const string PasswordResetSuccessLogMessageText = "PasswordResetSuccessLogMessageText"; 

        /// <summary>
        /// Gets the key for the PasswordText resource string.
        /// </summary>
        public const string PasswordText = "PasswordText"; 

        /// <summary>
        /// Gets the key for the PhoneFormatText resource string.
        /// </summary>
        public const string PhoneFormatText = "PhoneFormatText"; 

        /// <summary>
        /// Gets the key for the PhoneText resource string.
        /// </summary>
        public const string PhoneText = "PhoneText"; 

        /// <summary>
        /// Gets the key for the PoweredByText resource string.
        /// </summary>
        public const string PoweredByText = "PoweredByText"; 

        /// <summary>
        /// Gets the key for the PreferredLanguageText resource string.
        /// </summary>
        public const string PreferredLanguageText = "PreferredLanguageText"; 

        /// <summary>
        /// Gets the key for the ProfileImageUpdateSuccessText resource string.
        /// </summary>
        public const string ProfileImageUpdateSuccessText = "ProfileImageUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the ProfileSettingsText resource string.
        /// </summary>
        public const string ProfileSettingsText = "ProfileSettingsText"; 

        /// <summary>
        /// Gets the key for the ProfileText resource string.
        /// </summary>
        public const string ProfileText = "ProfileText"; 

        /// <summary>
        /// Gets the key for the RecoveryCodeFailLogText resource string.
        /// </summary>
        public const string RecoveryCodeFailLogText = "RecoveryCodeFailLogText"; 

        /// <summary>
        /// Gets the key for the RecoveryCodePromptText resource string.
        /// </summary>
        public const string RecoveryCodePromptText = "RecoveryCodePromptText"; 

        /// <summary>
        /// Gets the key for the RecoveryCodeSuccessLogText resource string.
        /// </summary>
        public const string RecoveryCodeSuccessLogText = "RecoveryCodeSuccessLogText"; 

        /// <summary>
        /// Gets the key for the RecoveryCodeVerificationText resource string.
        /// </summary>
        public const string RecoveryCodeVerificationText = "RecoveryCodeVerificationText"; 

        /// <summary>
        /// Gets the key for the RefreshText resource string.
        /// </summary>
        public const string RefreshText = "RefreshText"; 

        /// <summary>
        /// Gets the key for the RegisterNewAccountText resource string.
        /// </summary>
        public const string RegisterNewAccountText = "RegisterNewAccountText"; 

        /// <summary>
        /// Gets the key for the RegisterText resource string.
        /// </summary>
        public const string RegisterText = "RegisterText"; 

        /// <summary>
        /// Gets the key for the RegisterWithText resource string.
        /// </summary>
        public const string RegisterWithText = "RegisterWithText"; 

        /// <summary>
        /// Gets the key for the RememberDeviceText resource string.
        /// </summary>
        public const string RememberDeviceText = "RememberDeviceText"; 

        /// <summary>
        /// Gets the key for the RememberMeText resource string.
        /// </summary>
        public const string RememberMeText = "RememberMeText"; 

        /// <summary>
        /// Gets the key for the RepositoriesText resource string.
        /// </summary>
        public const string RepositoriesText = "RepositoriesText"; 

        /// <summary>
        /// Gets the key for the ResetPasswordEmailSubjectText resource string.
        /// </summary>
        public const string ResetPasswordEmailSubjectText = "ResetPasswordEmailSubjectText"; 

        /// <summary>
        /// Gets the key for the ResetPasswordText resource string.
        /// </summary>
        public const string ResetPasswordText = "ResetPasswordText"; 

        /// <summary>
        /// Gets the key for the RevokeAccessText resource string.
        /// </summary>
        public const string RevokeAccessText = "RevokeAccessText"; 

        /// <summary>
        /// Gets the key for the SearchButtonText resource string.
        /// </summary>
        public const string SearchButtonText = "SearchButtonText"; 

        /// <summary>
        /// Gets the key for the SecondsText resource string.
        /// </summary>
        public const string SecondsText = "SecondsText"; 

        /// <summary>
        /// Gets the key for the SecurityEventsReportDescriptionText resource string.
        /// </summary>
        public const string SecurityEventsReportDescriptionText = "SecurityEventsReportDescriptionText"; 

        /// <summary>
        /// Gets the key for the SecurityEventsReportLabelText resource string.
        /// </summary>
        public const string SecurityEventsReportLabelText = "SecurityEventsReportLabelText"; 

        /// <summary>
        /// Gets the key for the SetLockDatetTimeText resource string.
        /// </summary>
        public const string SetLockDatetTimeText = "SetLockDatetTimeText"; 

        /// <summary>
        /// Gets the key for the SettingsText resource string.
        /// </summary>
        public const string SettingsText = "SettingsText"; 

        /// <summary>
        /// Gets the key for the SigningKeyExceptionErrorText resource string.
        /// </summary>
        public const string SigningKeyExceptionErrorText = "SigningKeyExceptionErrorText"; 

        /// <summary>
        /// Gets the key for the SigningKeyFromStoreThumbprintText resource string.
        /// </summary>
        public const string SigningKeyFromStoreThumbprintText = "SigningKeyFromStoreThumbprintText"; 

        /// <summary>
        /// Gets the key for the SigningKeyThumbprintNotFoundText resource string.
        /// </summary>
        public const string SigningKeyThumbprintNotFoundText = "SigningKeyThumbprintNotFoundText"; 

        /// <summary>
        /// Gets the key for the SignInText resource string.
        /// </summary>
        public const string SignInText = "SignInText"; 

        /// <summary>
        /// Gets the key for the SignInToYourAccountText resource string.
        /// </summary>
        public const string SignInToYourAccountText = "SignInToYourAccountText"; 

        /// <summary>
        /// Gets the key for the SignInWithText resource string.
        /// </summary>
        public const string SignInWithText = "SignInWithText"; 

        /// <summary>
        /// Gets the key for the SignOutPromptText resource string.
        /// </summary>
        public const string SignOutPromptText = "SignOutPromptText"; 

        /// <summary>
        /// Gets the key for the SignOutText resource string.
        /// </summary>
        public const string SignOutText = "SignOutText"; 

        /// <summary>
        /// Gets the key for the SignOutTitleText resource string.
        /// </summary>
        public const string SignOutTitleText = "SignOutTitleText"; 

        /// <summary>
        /// Gets the key for the StandardConcurrentText resource string.
        /// </summary>
        public const string StandardConcurrentText = "StandardConcurrentText"; 

        /// <summary>
        /// Gets the key for the StandardNamedText resource string.
        /// </summary>
        public const string StandardNamedText = "StandardNamedText"; 

        /// <summary>
        /// Gets the key for the StartupBackgroundWorkerErrorText resource string.
        /// </summary>
        public const string StartupBackgroundWorkerErrorText = "StartupBackgroundWorkerErrorText"; 

        /// <summary>
        /// Gets the key for the StartupMessageText resource string.
        /// </summary>
        public const string StartupMessageText = "StartupMessageText"; 

        /// <summary>
        /// Gets the key for the StringLengthRequirementsText resource string.
        /// </summary>
        public const string StringLengthRequirementsText = "StringLengthRequirementsText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsApplicationDetailsLabelText resource string.
        /// </summary>
        public const string SubscriptionsApplicationDetailsLabelText = "SubscriptionsApplicationDetailsLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsApplicationNameLabelText resource string.
        /// </summary>
        public const string SubscriptionsApplicationNameLabelText = "SubscriptionsApplicationNameLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsDetailsTitleText resource string.
        /// </summary>
        public const string SubscriptionsDetailsTitleText = "SubscriptionsDetailsTitleText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsDomainLabelText resource string.
        /// </summary>
        public const string SubscriptionsDomainLabelText = "SubscriptionsDomainLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsNoneFoundText resource string.
        /// </summary>
        public const string SubscriptionsNoneFoundText = "SubscriptionsNoneFoundText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsOrganizationLabelText resource string.
        /// </summary>
        public const string SubscriptionsOrganizationLabelText = "SubscriptionsOrganizationLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsRenewalDateLabelText resource string.
        /// </summary>
        public const string SubscriptionsRenewalDateLabelText = "SubscriptionsRenewalDateLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionsText resource string.
        /// </summary>
        public const string SubscriptionsText = "SubscriptionsText"; 

        /// <summary>
        /// Gets the key for the SubscriptionSubscriptionTypeLabelText resource string.
        /// </summary>
        public const string SubscriptionSubscriptionTypeLabelText = "SubscriptionSubscriptionTypeLabelText"; 

        /// <summary>
        /// Gets the key for the SubscriptionUpdatedSuccessfullyText resource string.
        /// </summary>
        public const string SubscriptionUpdatedSuccessfullyText = "SubscriptionUpdatedSuccessfullyText"; 

        /// <summary>
        /// Gets the key for the SuccessText resource string.
        /// </summary>
        public const string SuccessText = "SuccessText"; 

        /// <summary>
        /// Gets the key for the TenantsText resource string.
        /// </summary>
        public const string TenantsText = "TenantsText"; 

        /// <summary>
        /// Gets the key for the TermsAgreeRequiredText resource string.
        /// </summary>
        public const string TermsAgreeRequiredText = "TermsAgreeRequiredText"; 

        /// <summary>
        /// Gets the key for the TermsAndConditionsText resource string.
        /// </summary>
        public const string TermsAndConditionsText = "TermsAndConditionsText"; 

        /// <summary>
        /// Gets the key for the TimezoneText resource string.
        /// </summary>
        public const string TimezoneText = "TimezoneText"; 

        /// <summary>
        /// Gets the key for the TwoFactorAuthenticationCodeText resource string.
        /// </summary>
        public const string TwoFactorAuthenticationCodeText = "TwoFactorAuthenticationCodeText"; 

        /// <summary>
        /// Gets the key for the TwoFactorAuthenticationEnableText resource string.
        /// </summary>
        public const string TwoFactorAuthenticationEnableText = "TwoFactorAuthenticationEnableText"; 

        /// <summary>
        /// Gets the key for the TwoFactorAuthenticationPromptText resource string.
        /// </summary>
        public const string TwoFactorAuthenticationPromptText = "TwoFactorAuthenticationPromptText"; 

        /// <summary>
        /// Gets the key for the TwoFactorAuthenticationSuccessLogText resource string.
        /// </summary>
        public const string TwoFactorAuthenticationSuccessLogText = "TwoFactorAuthenticationSuccessLogText"; 

        /// <summary>
        /// Gets the key for the TwoFactorAuthenticationText resource string.
        /// </summary>
        public const string TwoFactorAuthenticationText = "TwoFactorAuthenticationText"; 

        /// <summary>
        /// Gets the key for the TwoFactorRecoveryPromptText resource string.
        /// </summary>
        public const string TwoFactorRecoveryPromptText = "TwoFactorRecoveryPromptText"; 

        /// <summary>
        /// Gets the key for the TwoFactorUserNotFoundText resource string.
        /// </summary>
        public const string TwoFactorUserNotFoundText = "TwoFactorUserNotFoundText"; 

        /// <summary>
        /// Gets the key for the UnlockText resource string.
        /// </summary>
        public const string UnlockText = "UnlockText"; 

        /// <summary>
        /// Gets the key for the UnlockUserConfirmationText resource string.
        /// </summary>
        public const string UnlockUserConfirmationText = "UnlockUserConfirmationText"; 

        /// <summary>
        /// Gets the key for the UnlockUserText resource string.
        /// </summary>
        public const string UnlockUserText = "UnlockUserText"; 

        /// <summary>
        /// Gets the key for the UpdatedReportLabelText resource string.
        /// </summary>
        public const string UpdatedReportLabelText = "UpdatedReportLabelText"; 

        /// <summary>
        /// Gets the key for the UpdateOrganizationText resource string.
        /// </summary>
        public const string UpdateOrganizationText = "UpdateOrganizationText"; 

        /// <summary>
        /// Gets the key for the UpdateProfileText resource string.
        /// </summary>
        public const string UpdateProfileText = "UpdateProfileText"; 

        /// <summary>
        /// Gets the key for the UpdateText resource string.
        /// </summary>
        public const string UpdateText = "UpdateText"; 

        /// <summary>
        /// Gets the key for the UpdateUserText resource string.
        /// </summary>
        public const string UpdateUserText = "UpdateUserText"; 

        /// <summary>
        /// Gets the key for the UserAccountLockedMessageText resource string.
        /// </summary>
        public const string UserAccountLockedMessageText = "UserAccountLockedMessageText"; 

        /// <summary>
        /// Gets the key for the UserDeleteAccount resource string.
        /// </summary>
        public const string UserDeleteAccount = "UserDeleteAccount"; 

        /// <summary>
        /// Gets the key for the UserDetailsText resource string.
        /// </summary>
        public const string UserDetailsText = "UserDetailsText"; 

        /// <summary>
        /// Gets the key for the UseRecoveryCodeText resource string.
        /// </summary>
        public const string UseRecoveryCodeText = "UseRecoveryCodeText"; 

        /// <summary>
        /// Gets the key for the UserInformationUpdatedSuccessfullyText resource string.
        /// </summary>
        public const string UserInformationUpdatedSuccessfullyText = "UserInformationUpdatedSuccessfullyText"; 

        /// <summary>
        /// Gets the key for the UserNameDeniedConsentErrorText resource string.
        /// </summary>
        public const string UserNameDeniedConsentErrorText = "UserNameDeniedConsentErrorText"; 

        /// <summary>
        /// Gets the key for the UserNameIncorrectText resource string.
        /// </summary>
        public const string UserNameIncorrectText = "UserNameIncorrectText"; 

        /// <summary>
        /// Gets the key for the UserNameInvalidText resource string.
        /// </summary>
        public const string UserNameInvalidText = "UserNameInvalidText"; 

        /// <summary>
        /// Gets the key for the UserNameNotFoundErrorText resource string.
        /// </summary>
        public const string UserNameNotFoundErrorText = "UserNameNotFoundErrorText"; 

        /// <summary>
        /// Gets the key for the UserNameText resource string.
        /// </summary>
        public const string UserNameText = "UserNameText"; 

        /// <summary>
        /// Gets the key for the UsersText resource string.
        /// </summary>
        public const string UsersText = "UsersText"; 

        /// <summary>
        /// Gets the key for the UserText resource string.
        /// </summary>
        public const string UserText = "UserText"; 

        /// <summary>
        /// Gets the key for the VerificationCodeInvalidText resource string.
        /// </summary>
        public const string VerificationCodeInvalidText = "VerificationCodeInvalidText"; 

        /// <summary>
        /// Gets the key for the VerificationCodeText resource string.
        /// </summary>
        public const string VerificationCodeText = "VerificationCodeText"; 

        /// <summary>
        /// Gets the key for the VerifyClickResendCodeMessageText resource string.
        /// </summary>
        public const string VerifyClickResendCodeMessageText = "VerifyClickResendCodeMessageText"; 

        /// <summary>
        /// Gets the key for the VerifyEmailAndPhoneText resource string.
        /// </summary>
        public const string VerifyEmailAndPhoneText = "VerifyEmailAndPhoneText"; 

        /// <summary>
        /// Gets the key for the VerifyEmailSubjectText resource string.
        /// </summary>
        public const string VerifyEmailSubjectText = "VerifyEmailSubjectText"; 

        /// <summary>
        /// Gets the key for the VerifyEmailSuggestMessageText resource string.
        /// </summary>
        public const string VerifyEmailSuggestMessageText = "VerifyEmailSuggestMessageText"; 

        /// <summary>
        /// Gets the key for the VerifyEmailText resource string.
        /// </summary>
        public const string VerifyEmailText = "VerifyEmailText"; 

        /// <summary>
        /// Gets the key for the VerifyEmailWarningText resource string.
        /// </summary>
        public const string VerifyEmailWarningText = "VerifyEmailWarningText"; 

        /// <summary>
        /// Gets the key for the VerifyPhoneSuggestMessageText resource string.
        /// </summary>
        public const string VerifyPhoneSuggestMessageText = "VerifyPhoneSuggestMessageText"; 

        /// <summary>
        /// Gets the key for the VerifyPhoneText resource string.
        /// </summary>
        public const string VerifyPhoneText = "VerifyPhoneText"; 

        /// <summary>
        /// Gets the key for the VerifyPluralHaveText resource string.
        /// </summary>
        public const string VerifyPluralHaveText = "VerifyPluralHaveText"; 

        /// <summary>
        /// Gets the key for the VerifySingularHasText resource string.
        /// </summary>
        public const string VerifySingularHasText = "VerifySingularHasText"; 

        /// <summary>
        /// Gets the key for the VerifyText resource string.
        /// </summary>
        public const string VerifyText = "VerifyText"; 

        /// <summary>
        /// Gets the key for the WarningText resource string.
        /// </summary>
        public const string WarningText = "WarningText"; 

        /// <summary>
        /// Gets the key for the WebsiteText resource string.
        /// </summary>
        public const string WebsiteText = "WebsiteText"; 

        /// <summary>
        /// Gets the key for the YesText resource string.
        /// </summary>
        public const string YesText = "YesText"; 
    }
}
